version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - ${RPROXY_TUNNEL}

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log"
    ports:
      - "${TRAEFIK_DASHBOARD_HOST_IP:-127.0.0.1}:${TRAEFIK_DASHBOARD_HOST_MAPPED_PORT:-}:${TRAEFIK_DASHBOARD_CONTAINER_PORT:-8080}"   # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      - ./logs:/logs
      - ./dynamic:/dynamic:ro
    networks:
      - ${RPROXY_TUNNEL}
      - ${RPROXY_GENERAL}

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`who.${BASE_DOMAIN_1}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - ${RPROXY_GENERAL}

networks:
  traefik-tunnel:
    external: true
    name: ${RPROXY_TUNNEL}

  traefik-general:
    external: true
    name: ${RPROXY_GENERAL}
