# ./config/traefik.yaml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true  # Do not allow insecure external access to the dashboard

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: "${ACME_EMAIL}"      # <-- Replace with your ACME registration email      # <-- Replace with your ACME registration email
      storage: /acme/acme.json                 # ACME storage file (mapped from ./acme/acme.json)
      dnsChallenge:
        provider: cloudflare

# Logging configuration:
log:
  level: INFO
  filePath: /logs/traefik.log                # General Traefik logs (stored in ./logs/traefik.log)

accessLog:
  filePath: /logs/access.log                 # HTTP access logs (stored in ./logs/access.log)